services:
  postgres:
    image: postgres:16-alpine
    container_name: cha_de_panela_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cha_de_panela
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - cha_de_panela_postgres_data:/var/lib/postgresql/data

volumes:
  cha_de_panela_postgres_data:
